### ISSUE TITLE
NoSuchMethodError: reevaluateSystemTheme(java.lang.Boolean)

### ISSUE THREAD

**Issue by Dimon-015** [Mahmud0808/ColorBlendr#1]
[Device Brand]: Xiaomi
[Device Model]: M2007J3SY
[Display]: TQ3A.230805.001
[Android Version]: 13
[Android API Level]: 33
[System Locale]: ru_RU
[Process ID]: 2981
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: com.android.systemui
[Version Name]: 13
[Version Code]: 33
[Target SDK]: 33
[Min SDK]: 33
[Error Type]: JVM
[Crash Time]: 2023-12-06T19:35:03.228
[Stack Trace]:
java.lang.NoSuchMethodError: com.google.android.systemui.theme.ThemeOverlayControllerGoogle#reevaluateSystemTheme(java.lang.Boolean)
 at de.robv.android.xposed.XposedHelpers.lambda$findMethodBestMatch$5(XposedHelpers.java:565)
 at de.robv.android.xposed.XposedHelpers$$ExternalSyntheticLambda7.get(Unknown Source:2)
 at java.util.Optional.orElseThrow(Optional.java:404)
 at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:565)
 at de.robv.android.xposed.XposedHelpers.findMethodBestMatch(XposedHelpers.java:575)
 at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1454)
 at com.drdisagree.colorblendr.xposed.modules.MonetColors.updatePrefs(MonetColors.java:66)
 at com.drdisagree.colorblendr.config.XPrefs.loadEverything(XPrefs.java:29)
 at com.drdisagree.colorblendr.config.XPrefs.lambda$static$0(XPrefs.java:14)
 at com.drdisagree.colorblendr.config.XPrefs$$ExternalSyntheticLambda0.onSharedPreferenceChanged(Unknown Source:0)
 at com.crossbowffs.remotepreferences.RemotePreferences$PreferenceContentObserver.onChange(RemotePreferences.java:522)
 at android.database.ContentObserver.onChange(ContentObserver.java:170)
 at android.database.ContentObserver.onChange(ContentObserver.java:188)
 at android.database.ContentObserver.onChange(ContentObserver.java:224)
 at android.database.ContentObserver.lambda$dispatchChange$0$android-database-ContentObserver(ContentObserver.java:304)
 at android.database.ContentObserver$$ExternalSyntheticLambda0.run(Unknown Source:10)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7959)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)

**Comment by Dimon-015** [comment]
occurs when trying to activate pitch black.

**Comment by Dimon-015** [comment]
> Which rom? Android version?

My log is cut off by Github.  I have Android 13. Pixel Experience.

**Comment by Dimon-015** [comment]
> Which rom? Android version?

![Uploading Screenshot_20231206-195130_AyuGram.png…]()

**Comment by Mahmud0808** [comment]
Share logs from LSPosed as well

**Comment by Dimon-015** [comment]
> Share logs from LSPosed as well

[LSPosed_2023-12-06T23_14_04.223885.zip](https://github.com/Mahmud0808/ColorBlendr/files/13591148/LSPosed_2023-12-06T23_14_04.223885.zip)
