### ISSUE TITLE
Allow full control in OneUI?

### ISSUE THREAD

**Issue by nekorubu** [Mahmud0808/ColorBlendr#42]
In Repainter, you can get [full control over the system colors in Samsung's OneUI](https://www.androidpolice.com/repainter-android-12-how-to/#repainter-on-samsung-one-ui-4), even with Shizuku. As for me, Repainter's full control still works on OneUI 5, though I have seen that it doesn't seem to work at all on OneUI 6. Is it possible to have the app get full control over the system palette on OneUI even with Shizuku like Repainter can?

**Comment by Mahmud0808** [comment]
Unfortunately I don't have a Samsung device.

**Comment by nekorubu** [comment]
Oh, I see. Is there any way I can help?

**Comment by Mahmud0808** [comment]
Probably not but thanks. It's easier to develop and test on device I own instead of building blindly and testing by others.

Maybe any dev who has oneui can help, it's an open source project, you are free to fork, modify and release your own build.

**Comment by coggy9** [comment]
Samsung has a free [remote testing service](https://developer.samsung.com/remote-test-lab) if you want to test on Samsung devices.

**Comment by Mahmud0808** [comment]
> Samsung has a free [remote testing service](https://developer.samsung.com/remote-test-lab) if you want to test on Samsung devices.

Can any of you provide SystemUI.apk and framework-res.apk of samsung oneui 6? Then I can maybe make some progress.

**Comment by coggy9** [comment]
Sure. [Here](https://nothing.coggy9.dev/temp/systemapks.zip) they are from a Z Fold 5 with the latest One UI 6.0 build.

**Comment by Mahmud0808** [comment]
> Samsung has a free [remote testing service](https://developer.samsung.com/remote-test-lab) if you want to test on Samsung devices.

I just created an account and it gave me 10 free credits. Now everytime I got in that link, it asks me to login, after login it reloads the test lab page and asks to login again, stuck in a login loop lol.

**Comment by muznyo** [comment]
> > Samsung has a free [remote testing service](https://developer.samsung.com/remote-test-lab) if you want to test on Samsung devices.
> 
> I just created an account and it gave me 10 free credits. Now everytime I visit that link, it asks me to login, after login it reloads the test lab page and asks to login again, stuck in a login loop lol.

I just created an account too and it worked for me? What browser do you use? i used firefox

**Comment by Mahmud0808** [comment]
Chrome on windows 11. I will try again later in incognito mode. Probably that 10 credits won't be enough at all, but let's give it a shot.

**Comment by muznyo** [comment]
> Chrome on windows 11. I will try again later in incognito mode. Probably that 10 credits won't be enough at all, but let's give it a shot.

i think credits wont be a problem 
![image](https://github.com/Mahmud0808/ColorBlendr/assets/24987471/0cc5a657-4e5f-46ab-94ca-af47eae4b772)

**Comment by Xisrr1** [comment]
Oh please no, repainter ruins the default one UI theme if you use it and you cannot use the phone's default color palette again until you factory reset. I really like that this app is only for apps color and not the system theme.

**Comment by Xisrr1** [comment]
> > Oh please no, repainter ruins the default one UI theme if you use it and you cannot use the phone's default color palette again until you factory reset. I really like that this app is only for apps color and not the system theme. 
> 
> You don't need to factory reset  Just stop the app again and the color palette will work again  
> 

When I used repainter even after disabling it won't let the default color palette settings work.

**Comment by Mahmud0808** [comment]
Unfortunately I still can't login in Samsung Test Lab. It keeps looping the login scree, I login and go to choose a device, it again asks me to login, and it keeps going on forever.

**Comment by Xisrr1** [comment]
Average Samsung experience

**Comment by RoootTheFox** [comment]
hi,
is there any way I can maybe help with/contribute to this?
I don't have a lot of experience in Android development (or Shizuku), but I do have general programming knowledge/experience and I'd love if I could contribute to this somehow.
I have the following hardware available to me:
- Samsung Galaxy S23+ (primary phone, OneUI 6)
- Samsung Galaxy A51 (old phone, OneUI 5)

(I'd like to avoid targeting my main phone first, since I rely on it and don't want things to break)

Can you give me steps for getting started with this (e.g. important Material You/SystemUI internals)?

Also, thank you for creating this project in the first place ❤️

**Comment by Mahmud0808** [comment]
> Can you give me steps for getting started with this (e.g. important Material You/SystemUI internals)?

I can send a test build which I was working on blindly without any Samsung device :") don't get hopes too high cause totally blind build and most probably won't work.

**Comment by RoootTheFox** [comment]
Sure! If I can help in any way that's great :3 
I'll test it first on my old phone (OneUI 5) in case something breaks, if it works there I'll test on my main phone. I'm not home yet though, so I don't have access to my old phone atm (will be in a couple hours)

**Comment by Mahmud0808** [comment]
> Sure! If I can help in any way that's great :3 I'll test it first on my old phone (OneUI 5) in case something breaks, if it works there I'll test on my main phone. I'm not home yet though, so I don't have access to my old phone atm (will be in a couple hours)

[ColorBlendr v1.2 Debug Samsung.zip](https://github.com/Mahmud0808/ColorBlendr/files/14433789/ColorBlendr.v1.2.Debug.Samsung.zip)
Here you go. Not in a hurry ofcourse.

**Comment by coggy9** [comment]
Tried it on my Fold 5, and it crashes when tapping a color.

```
FATAL EXCEPTION: main
Process: com.drdisagree.colorblendr, PID: 24753
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.lang.Number
	at com.drdisagree.colorblendr.utils.MiscUtil.convertToIntArray(MiscUtil.java:65)
	at com.drdisagree.colorblendr.utils.OverlayManager.applyFabricatedColors(OverlayManager.java:221)
	at com.drdisagree.colorblendr.ui.fragments.ColorsFragment.lambda$addColorsToContainer$14(ColorsFragment.java:422)
	at com.drdisagree.colorblendr.ui.fragments.ColorsFragment.$r8$lambda$rieRlpZVMi0wGsq3TFo523NnDCQ(ColorsFragment.java:0)
	at com.drdisagree.colorblendr.ui.fragments.ColorsFragment$$ExternalSyntheticLambda8.onClick(R8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:8043)
	at android.view.View.performClickInternal(View.java:8020)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31867)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8913)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by Mahmud0808** [comment]
[ColorBlendr v1.2.zip](https://github.com/Mahmud0808/ColorBlendr/files/14434627/ColorBlendr.v1.2.zip)
What about this one?

**Comment by RoootTheFox** [comment]
just a small question - how (un)likely is it that this will break the system? (and if it does, would it be hard to recover without factory resetting?)
asking mostly out of curiosity

**Comment by coggy9** [comment]
Doesn't crash, but nothing changes. I'll get a logcat later today if needed. 

https://github.com/Mahmud0808/ColorBlendr/assets/352207/937f4455-8707-49f4-a390-09828f376560

**Comment by RoootTheFox** [comment]
@coggy9 iirc Repainter required you to reboot after applying on OneUI, I assume the same applies to ColorBlendr(?)

**Comment by coggy9** [comment]
You're correct, but even after rebooting, nothing changed.

**Comment by RoootTheFox** [comment]
> Doesn't crash, but nothing changes. I'll get a logcat later today if needed.
> 
>  Screen.Recording.20240228.074027.Colorblendr.mp4

@coggy9 for the actual Samsung UI/OneUI elements you need to use Samsung's Theme Park (Galaxy Store), can you try a Material You app? (e.g. Google Translate)

**Comment by coggy9** [comment]
![Screenshot_20240228_075701_Translate](https://github.com/Mahmud0808/ColorBlendr/assets/352207/b74b9d03-f25e-44a1-8025-b4f0cfc49610)
Translate is a default blue color, but Gboard, which is set to use the dynamic colors, is still the pink color I selected before using ColorBlendr. 🤔

**Comment by Mahmud0808** [comment]
Well, I've hit my limit on what I can do here. Maybe a developer who has a Samsung device could pitch in and lend a hand with this.

**Comment by RoootTheFox** [comment]
as i said, I'd love to help, but I have no idea where to start.

**Comment by Mahmud0808** [comment]
> as i said, I'd love to help, but I have no idea where to start.

It's quite hard for me to explain as you said you don't have any experience with android application. You first need to find out which method is used for applying themes in OverlayManager class of framework. Then you need to study how exactly it applies colors, like what parameters are being used etc. Then you have to replicate the same behavior using Shizuku API. If it throws security warning, then you need to root to call that method. I hope that will make it little bit more clear.

**Comment by RoootTheFox** [comment]
thanks! ill see if i can maybe get something working (although I doubt I will lmao)

**Comment by RoootTheFox** [comment]
@Mahmud0808 I just tried the last build you posted, and it seems to have insufficient permissions to create a runtime resource overlay:
![Screenshot_20240229_095330_LogFox](https://github.com/Mahmud0808/ColorBlendr/assets/78933889/d1e6431b-9c23-42a9-8c68-c61a6fe22ec1)

[text log](https://pastebin.com/raw/yZQ9ckRK)

From my experiments, applying RROs through Galaxy Themes works fine (that is how 1st party themes get applied), so I have a theory on what could work:
- generate overlay package\*, install it to the system
then:
- `settings put system THEMEKEY OVERLAYPKGNAME` where `THEMEKEY` is any of the following: 
  - `current_sec_active_themepackage`
  - `current_sec_aod_theme_package`
  - `current_sec_appicon_theme_package`
  - `current_sec_home_theme_package`
  - `current_sec_iris_theme_package`
  - `current_sec_wallpaper_theme_package`
(not sure which of these actually work, or if they work at all, but OneUI sets those values so I'm assuming they work)
 - reboot (or reload theme overlays manually somehow?)

*\* i am not sure if this needs to be a full-blown OneUI theme (with RRO apks nested in assets/) or if it can be just a single overlay apk*

I'm currently still in the process of reverse engineering and researching the OneUI theme format in an attempt to (more or less) fully understand how a OneUI theme package is structured, what keys/files/etc are needed and ways to apply them

*(side note: the OneUI themes seem to have custom AndroidManifest.xml keys for which frameworks(?) are targeted, as well as some samsung-specific permission for themes (need to do more research on that))*

**Comment by Mahmud0808** [comment]
> generate overlay package*, install it to the system

This can't be done without root I guess. Also the log says it requires root. So last hope is samsung-specific permission for themes that if we can grant through Shizuku, it theoretically should work.

Let's see what you can find. Good luck. :) Sadly can't help much in this case without a samsung device (and don't want one either). :(

**Comment by RoootTheFox** [comment]
[I've made paste with some (maybe) helpful information](https://pastebin.com/raw/RRQEJMU7) (overlay list and the settings values)

the overlays/theme were installed using Hex Installer and applied through Galaxy Themes (`com.samsung.High_contrast_theme_II.plus` is the package name for the generated theme)

<sub>I'll probably keep infodumping here when I find new things, maybe someone else finds them useful if I can't get anything to work.</sub>

**Comment by jack5mikemotown** [comment]
Sorry if I'm misunderstanding something here, should this app be working with OneUI 6 or is that what's being figured out here? I'm not seeing any color changes, running with shizuku. None of the UI in the app or elsewhere seems to update to reflect it

**Comment by Virkkunen** [comment]
> Sorry if I'm misunderstanding something here, should this app be working with OneUI 6 or is that what's being figured out here? I'm not seeing any color changes, running with shizuku. None of the UI in the app or elsewhere seems to update to reflect it

This app does work with One UI 6, but in a limited way, it can only set the main colour and the style. If you've set your colour with Theme Park, then you might not see any changes in most apps, apart from some that weren't respecting the dynamic colour theme (eg. most Google apps, the new Beeper app).

**Comment by zelodev** [comment]
> > generate overlay package*, install it to the system
> 
> This can't be done without root I guess. Also the log says it requires root. So last hope is samsung-specific permission for themes that if we can grant through Shizuku, it theoretically should work.
> 
> Let's see what you can find. Good luck. :) Sadly can't help much in this case without a samsung device (and don't want one either). :(

to clarify this CAN be done without root. take a look at synergy

**Comment by Mahmud0808** [comment]
> to clarify this CAN be done without root. take a look at synergy

Synergy is both paid and not OSS. Can't check.

**Comment by Fede2782** [comment]
Hi, I'm pretty sure that these two links can help making this thing works. https://github.com/salvogiangri/KnoxPatch/blob/main/app/src/main/res/xml/sep_color_theme_meta.xml

https://github.com/salvogiangri/KnoxPatch/commits/main/app/src/main/res/xml/sep_color_theme_meta.xml

https://github.com/salvogiangri/KnoxPatch/blob/main/app/src/main/res/xml/sep_color_theme_meta.xml

Maybe taking a look at how theme park implements it could be useful too. Currently I don't have time but once I have a bit more I will surely try to understand more about how Samsung colors works.

**Comment by Mahmud0808** [comment]
> Hi, I'm pretty sure that these two links can help making this thing works. https://github.com/salvogiangri/KnoxPatch/blob/main/app/src/main/res/xml/sep_color_theme_meta.xml
> 
> https://github.com/salvogiangri/KnoxPatch/commits/main/app/src/main/res/xml/sep_color_theme_meta.xml
> 
> Maybe taking a look at how theme park implements it could be useful too. Currently I don't have time but once I have a bit more I will surely try to understand more about how Samsung colors works.

Apologies for the delayed response; I missed your message. Unfortunately, I still don't understand its purpose or how it works.

**Comment by MNLierman** [comment]
Hi, so I take it there isn't a new test version? The current version does indeed set the colors I pick but almost all options in ColorBlendr are grayed out. It actually doesn't seem to change much more than what is already available in the Samsung Themes option from Settings.

Why does Samsung have to be a smelly pile of dog crap? This is 2025 and the end-user can't adjust the colors? It's not Material You without the **_YOU_**. 

The themes is Samsung store are just as terrible. It's like they purposely only allow Korean anime themes, and or have a very expensive very strict approval process. Otherwise, where's all the themes. With Samsung + Android 10 and 11 you used to be able to find Pixel and AOSP style themes with the stock default colors instead of Samsung's garbage colors. The new One UI 7 colors are so nasty. It's blue and gray. The gray replaced the off-white for dialogs and windows – it leaves a very nasty look and makes me feel sick. 🤢 

Honestly just about had it with Samsung. No customization, no unlocking, won't listen to feedback, strikes in Korea delayed Android 15 and Google is already finishing Android 16. It's time we send Samsung feedback and vote with our wallet if they don't listen. Don't think I'll be picking Samsung again with my next phone. 

Dev, I think it would be good to add a Q/A to the ReadMe specifically for Samsung to make Samsung phone limitations clear. 

“Q: I have a Samsung phone and most options are grayed out, and the colors are extremely limited, what's the deal here?
A: Samsung doesn't believe in Material _You_. This app attempts to give you the best you can get. Send Samsung feedback to fully support Material You with fully customizable colors, or vote with your wallet.” 

I hope the recent developments and recent comments give you something to work with.

**Comment by Phone-Guru** [comment]
The latest version is working for me on rooted galaxy s10 running OneUI 5.1.  Google apps using Material You look great.

**Comment by RoootTheFox** [comment]
This issue is about full control *without* root (Shizuku) - though I gotta add that I've noticed that Samsung have been getting increasingly restrictive with nearly each software update, to the point where I have to use very convoluted workarounds to even get a custom theme to apply (Hex Installer in my case, OneUI 6.1)

At this point, I highly doubt this will be possible (or at least feasible) going forward, and I for myself have decided that I'll switch away from Samsung for good at some point in the future to regain some freedom.

**Comment by Phone-Guru** [comment]
I use substratum

**Comment by Kevinco1** [comment]
> to clarify this CAN be done without root. take a look at synergy

Synergy worked up to A11 before Google made changes to overlays. Same reason why Substratum has required root since then as well

**Comment by Kevinco1** [comment]
For anyone that wants full control in OneUI use the Substratum theme, Ava

**Comment by Phone-Guru** [comment]
> For anyone that wants full control in OneUI use the Substratum theme, Av

I'm having an issue with Substratum on OneUI 8. Overlays will compile but stay inactive. Some will suddenly activate but updating deactivates again. Any idea what's going on?

**Comment by Kevinco1** [comment]
> > For anyone that wants full control in OneUI use the Substratum theme, Av
> 
> I'm having an issue with Substratum on OneUI 8. Overlays will compile but stay inactive. Some will suddenly activate but updating deactivates again. Any idea what's going on?

As of now Substratum is compatible with A16 AOSP and below, but with Samsung only works up to A15 OneUI7

**Comment by Phone-Guru** [comment]
> > > For anyone that wants full control in OneUI use the Substratum theme, Av
> > 
> > 
> > I'm having an issue with Substratum on OneUI 8. Overlays will compile but stay inactive. Some will suddenly activate but updating deactivates again. Any idea what's going on?
> 
> As of now Substratum is compatible with A16 AOSP and below, but with Samsung only works up to A15 OneUI7

It does work a bit though on OneUI 8.  One of my overlays worked straight away, others don't but then suddenly did but stopped again after updating. For the first few OneUI 8 betas it worked perfectly and for the latest OneUI7 it had this issue.

**Comment by Kevinco1** [comment]
> > > > For anyone that wants full control in OneUI use the Substratum theme, Av
> > > 
> > > 
> > > I'm having an issue with Substratum on OneUI 8. Overlays will compile but stay inactive. Some will suddenly activate but updating deactivates again. Any idea what's going on?
> > 
> > 
> > As of now Substratum is compatible with A16 AOSP and below, but with Samsung only works up to A15 OneUI7
> 
> It does work a bit though on OneUI 8. One of my overlays worked straight away, others don't but then suddenly did but stopped again after updating. For the first few OneUI 8 betas it worked perfectly and for the latest OneUI7 it had this issue.

What theme are you using, AVA? It hasn't been updated since July and there is no OneUI8 option so if you are building with OneUI7 overlays that's why it's so inconsistent

**Comment by Phone-Guru** [comment]
Using my own theme which, as stated, has worked on OneUI 8.  Currently only working on eBay. Was working on opera, xe currency, Gmail, Google maps before applying October security patch.

**Comment by Kevinco1** [comment]
> Using my own theme which, as stated, has worked on OneUI 8. Currently only working on eBay. Was working on opera, xe currency, Gmail, Google maps before applying October security patch.

What do you mean your own theme? Just to be clear I have been talking about Substratum. Ava specifically is designed for OneUI while other Substratum themes may work with OneUI but are designed for AOSP

**Comment by Mahmud0808** [comment]
Unfortunately this is not possible anymore on newer OneUI versions.
